version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - game-network

  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    depends_on:
      - server
    networks:
      - game-network
    # desativa o comando padrão para que você possa executá-lo manualmente, se quiser
    # ou mude 'command' para ['go', 'test', ...], caso queira que ele rode automaticamente
    command: ["tail", "-f", "/dev/null"] 
    
networks:
  game-network:
    driver: bridge