# usa a imagem do go
FROM golang:1.22-alpine as builder

# define o diretório de trabalho
WORKDIR /app

# copia os arquivos de código
COPY . .

# define o comando para rodar os testes
# CGO_ENABLED=0 garante um binário estático, e -race ativa o detector de race condition
CMD ["go", "test", "-v", "-run", "TestStressScenario", "-race"]